name: myWorkfloww

on:
  push:
    branches:
      - main

jobs:
  mo2men:
    runs-on: ubuntu-latest
    steps:
      - name: checking out whats up
        uses: actions/checkout@v6
        
      - name: main-step
        run: 
         |
         chmod +x bashscript.sh
         ./bashscript.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt
