name: myWorkfloww

on:
  push:
    branches:
      - main

jobs:
  mo2men:
    runs-on: ubuntu-latest
    steps:
      - name: checking out whats up
        uses: actions/checkout@v6

      - name: adding upload artificatttooo
        uses: actions/upload-artifact@v4  
        with:
          path: dragon.txt

      - name: main-step
        run: 
         |
         chmod +x bashscript.sh
         ./bashscript.sh
