name: myWorkfloww

on:
  push:
    branches:
      - main

jobs:
  mo2men:
    runs-on: ubuntu-latest
    steps:
      - name: checking out whats up
        uses: actions/checkout@v6

      - name: main-step
        run: 
         |
         chmod +x bashscript.sh
         ./bashscript.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dragon-file
          path: dragon.txt

  job2:
    runs-on: ubuntu-latest
    name: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKER_USERNAME }}        
          password: ${{ vars.DOCKER_PASSWORD }}    

      - name: build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: user/app:latest
