name: myWorkfloww

on:
  push:
    branches:
      - main

jobs:
  mo2men:
    runs-on: ubuntu-latest
    steps:
      - name: checking out whats up
        uses: actions/checkout@v6

      - name: main-step
        run: 
         |
         chmod +x bashscipt.sh
         ./bashscript.sh
