name: Python ETL CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pandas numpy pytest
          pip install dbt-duckdb

      - name: Setup dbt Profile
        run: |
          mkdir -p ~/.dbt
          cat << EOF > ~/.dbt/profiles.yml
          testing_profile:
            target: dev
            outputs:
              dev:
                type: duckdb
                path: dbt_test.duckdb
          EOF      

      - name: run dbt 
        run: | 
         dbt run 
         dbt test 
      
      - name: Execute Tests
        run: pytest test_script.py -v